spring:
  datasource:
    url: ${DATABASE_SOURCE:jdbc:mysql://localhost:3306/dev?useSSL=false}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:tripro123}
    driverClassName: com.mysql.cj.jdbc.Driver
