server:
  port: 8082
  servlet:
    context-path: /crawl-service
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:dev}?createDatabaseIfNotExist=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:tripro123}
    driverClassName: com.mysql.cj.jdbc.Driver
